version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: voyage_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: voyage_user
      MONGO_INITDB_ROOT_PASSWORD: voyage_pass
      MONGO_INITDB_DATABASE: voyage_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
    image: redis:7.2-alpine
    container_name: voyage_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: voyage_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://voyage_user:voyage_pass@mongodb:27017/voyage_db?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:
  redis_data: