version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: voyage_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: voyage_db
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
    image: redis:7.2-alpine
    container_name: voyage_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: voyage_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: sh -c "cd /app && PYTHONPATH=/app/src uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  seed:
    build: .
    container_name: voyage_seed
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: python scripts/seed_data.py
    profiles:
      - seed

volumes:
  mongodb_data:
  redis_data: